# Change payment service running port
server:
  port: 0

spring:
  application:
    name: payment-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        namespace: ${spring.profiles.active}
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    driver-class-name: org.postgresql.Driver
    username: ecommerce_usr
    password: qwerqwer
    url: jdbc:postgresql://localhost:8432/db_payment
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true