networks:
  ecommerce-net:
    external: true
volumes:
  keycloak-ecommerce-vol:
services:
  keycloak-ecommerce:
    image: quay.io/keycloak/keycloak:26.8.0
    container_name: keycloak-ecommerce
    ports:
      - "8888:8080"
    command: start # start keycloak server in production
    environment:
      # Database Configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ecommerce_pg:5432/db_keycloak
      KC_DB_USERNAME: ecommerce_usr
      KC_DB_PASSWORD: qwerqwer
      # Admin User (បណ្ដោះអាសន្ន)
      KC_BOOTSTRAP_ADMIN_USERNAME: temp_admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: temp_admin
      # Production Setting
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8888
      KC_HOSTNAME_URL: http://localhost:8888
      KC_HOSTNAME_ADMIN_URL: http://localhost:8888
      KC_HOSTNAME_STRICT: false               # set to true if HTTPS
      KC_HOSTNAME_STRICT_HTTPS: false         # set to true if HTTPS
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      #KC_HTTPS_PORT: 443
      KC_PROXY_HEADERS: xforwarded
      KC_CACHE: ispn
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      JAVA_OPTS_APPEND: "-Xms512m -Xmx2048m"
    volumes:
      - keycloak-ecommerce-vol:/opt/keycloak/data
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/conf:/opt/keycloak/conf
    networks:
      - ecommerce-net